apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2025-07-21T175037Z
  name: policy-exc-req-f3808s6107p-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - ReplicaSet
        names:
        - mydeploy-*
        namespaces:
        - testns
    - resources:
        kinds:
        - Deployment
        names:
        - mydeploy
        namespaces:
        - testns
    - resources:
        kinds:
        - Pod
        names:
        - mydeploy-*
        namespaces:
        - testns
