apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-devops
  name: nginx-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-devops
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-devops
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
