apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-demo
  labels:
    app: busybox-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-demo
  template:
    metadata:
      labels:
        app: busybox-demo
    spec:
      containers:
      - name: busybox
        image: busybox:1.36
        command: ["sh", "-c", "while true; do echo hello; sleep 5; done"]
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
